### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Ashbajawed** [WangYizhang01/MaskCycleGAN-with-oneflow#1]
an argument in args/cycleGAN_arg_parser.py is of pre-trained model. is any pretrained model available so we may test results ?

**Comment by WangYizhang01** [comment]
> an argument in args/cycleGAN_arg_parser.py is of pre-trained model. is any pretrained model available so we may test results ?

please refer to infer.sh.

**Comment by Ashbajawed** [comment]
got it thanks
